# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es
  contentDir: content/es
  title: Genómica Funcional
  params:
    description: Sitio del Laboratorio de Genómica Funcional de CICESE
  menu:
    main:
      - name: Acerca
        url: '#intro'
        weight: 1
      - name: Equipo de Trabajo
        url: '#people'
        weight: 20
      - name: Proyectos
        url: '#projects'
        weight: 30
      - name: Publicaciones
        url: publication/
        weight: 40
      - name: Cursos
        url: courses/
        weight: 50


